development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:974086eed3c5cadf82bfd2aa746ccfda@dory.redistogo.com:11549/
  channel_prefix: message_me_production
